version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: api_produtos
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: api-produtos
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: senha123
      DB_NAME: api_produtos
    ports:
      - "3000:3000"

volumes:
  db_data:
